version: 2
jobs:
  build:
    docker:
      - image: rocker/tidyverse:3.6.0

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run:
          name: Multilayer Histology Plots
          command: ./scripts/run_in_ci.sh Rscript analyses/sample-distribution-analysis/02-multilayer-plots.R
          